import type { AssetRole, ItemTextureAssetRole, ItemTextureDirection, ProjectAsset, RaceTextureAssetRole, RaceTextureDirection, RaceTextureGroup, RaceTextureVariant, StorytellerPortraitRole } from "./types";

export const raceTextureDirections: RaceTextureDirection[] = ["front", "side", "back"];
export const raceTextureGroups: RaceTextureGroup[] = ["body", "head"];
export const raceTextureVariants: RaceTextureVariant[] = ["shared", "male", "female"];

export const directionToRimWorldSuffix: Record<RaceTextureDirection, "south" | "east" | "north"> = {
  // In the editor UI we expose player-friendly names.
  // RimWorld's Graphic_Multi convention uses south/east/north; west is generated by mirroring/copying side.
  front: "south",
  side: "east",
  back: "north"
};

export const directionLabels: Record<RaceTextureDirection, string> = {
  front: "正面 Front",
  side: "侧面 Side",
  back: "背面 Back"
};

export const groupLabels: Record<RaceTextureGroup, string> = {
  body: "身体 Body",
  head: "头部 Head"
};

export function sanitizeDefName(input: string): string {
  const cleaned = input
    .trim()
    .replace(/[^A-Za-z0-9_]+/g, "_")
    .replace(/^_+/, "")
    .replace(/_+$/, "");

  if (!cleaned) return "CustomRace";
  if (/^[A-Za-z]/.test(cleaned)) return cleaned;
  return `Race_${cleaned}`;
}


export function sanitizeThingDefName(input: string, fallback = "CustomItem"): string {
  const base = sanitizeDefName(input || fallback);
  return /[0-9]$/.test(base) ? `${base}_Def` : base;
}

export function sanitizePackageId(input: string): string {
  return input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_.-]+/g, ".")
    .replace(/\.+/g, ".")
    .replace(/^\.|\.$/g, "") || "local.generated.mod";
}


export function packageIdFromModName(name: string, author = "remux"): string {
  const authorPart = sanitizePackageId(author || "local").replace(/[^a-z0-9]+/g, "") || "local";
  const namePart = sanitizePackageId(name || "generated.mod")
    .replace(/[^a-z0-9.]+/g, ".")
    .replace(/\.+/g, ".")
    .replace(/^\.|\.$/g, "") || "generated.mod";
  return sanitizePackageId(`${authorPart}.${namePart}`);
}

export function isProbablyAutoPackageId(packageId: string, modName?: string, author?: string): boolean {
  const normalized = sanitizePackageId(packageId);
  if (!normalized) return true;
  if (normalized === "remux.stonekinrace") return true;
  if (modName && normalized === packageIdFromModName(modName, author)) return true;
  return false;
}

export function sanitizeFolderName(input: string): string {
  return input
    .trim()
    .replace(/[\\/:*?"<>|]/g, "_")
    .replace(/\s+/g, "_")
    .slice(0, 80) || "RimWorld_Mod";
}

export function makeRaceTextureAssetRole(group: RaceTextureGroup, direction: RaceTextureDirection, variant: RaceTextureVariant = "shared"): RaceTextureAssetRole {
  return variant === "shared" ? `race.${group}.${direction}` : `race.${variant}.${group}.${direction}`;
}

export function parseRaceTextureAssetRole(role: AssetRole): { variant: RaceTextureVariant; group: RaceTextureGroup; direction: RaceTextureDirection } | null {
  const parts = role.split(".");
  if (parts[0] !== "race") return null;

  // Backward-compatible role used by older exports: race.body.front
  if (parts.length === 3) {
    const group = parts[1] as RaceTextureGroup;
    const direction = parts[2] as RaceTextureDirection;
    if (!raceTextureGroups.includes(group) || !raceTextureDirections.includes(direction)) return null;
    return { variant: "shared", group, direction };
  }

  // Gender-aware role: race.male.body.front / race.female.head.back
  if (parts.length === 4) {
    const variant = parts[1] as RaceTextureVariant;
    const group = parts[2] as RaceTextureGroup;
    const direction = parts[3] as RaceTextureDirection;
    if (!raceTextureVariants.includes(variant) || !raceTextureGroups.includes(group) || !raceTextureDirections.includes(direction)) return null;
    return { variant, group, direction };
  }

  return null;
}

export function normalizeRaceTexturePaths(params: {
  packageId: string;
  defName: string;
  variant?: RaceTextureVariant;
}) {
  const packageId = sanitizePackageId(params.packageId);
  const defName = sanitizeDefName(params.defName);
  const variant = params.variant || "shared";
  const variantFolder = variant === "shared" ? "" : `/${variant === "male" ? "Male" : "Female"}`;
  const base = `${packageId}/Races/${defName}${variantFolder}`;

  return {
    body: normalizeTextureGroup({ base, defName, group: "body", variant }),
    head: normalizeTextureGroup({ base, defName, group: "head", variant })
  };
}

function normalizeTextureGroup(params: { base: string; defName: string; group: RaceTextureGroup; variant: RaceTextureVariant }) {
  const groupFolder = params.group === "body" ? "Bodies" : "Heads";
  const baseNamePart = params.group === "body" ? "Body" : "Head";
  const variantName = params.variant === "shared" ? "" : `${params.variant === "male" ? "Male" : "Female"}_`;
  const namePart = `${variantName}${baseNamePart}`;
  const xmlTexturePath = `${params.base}/${groupFolder}/${params.defName}_${namePart}`;

  return {
    xmlTexturePath,
    directions: {
      front: makeDirectionalPath(xmlTexturePath, params.defName, namePart, "front"),
      side: makeDirectionalPath(xmlTexturePath, params.defName, namePart, "side"),
      back: makeDirectionalPath(xmlTexturePath, params.defName, namePart, "back")
    }
  };
}

function makeDirectionalPath(xmlTexturePath: string, defName: string, namePart: string, direction: RaceTextureDirection) {
  const suffix = directionToRimWorldSuffix[direction];

  return {
    normalizedFileName: `${defName}_${namePart}_${suffix}.png`,
    exportPath: `Textures/${xmlTexturePath}_${suffix}.png`,
    xmlTexturePath
  };
}

export function getGeneratedWestTexturePath(asset: ProjectAsset): string | null {
  const parsed = parseRaceTextureAssetRole(asset.role);
  if (!parsed || parsed.direction !== "side") return null;
  return `Textures/${asset.xmlTexturePath}_west.png`;
}

export function createRaceAsset(params: {
  file: File;
  role: RaceTextureAssetRole;
  packageId: string;
  defName: string;
}): ProjectAsset {
  const parsed = parseRaceTextureAssetRole(params.role);
  if (!parsed) throw new Error(`Invalid race texture role: ${params.role}`);

  const paths = normalizeRaceTexturePaths({
    packageId: params.packageId,
    defName: params.defName,
    variant: parsed.variant
  });
  const selected = paths[parsed.group].directions[parsed.direction];

  return {
    id: crypto.randomUUID(),
    role: params.role,
    originalName: params.file.name,
    mimeType: params.file.type || "image/png",
    sourceKind: "browser-file",
    file: params.file,
    normalizedFileName: selected.normalizedFileName,
    exportPath: selected.exportPath,
    xmlTexturePath: selected.xmlTexturePath,
    previewUrl: URL.createObjectURL(params.file)
  };
}

export function refreshRaceAssetPath(params: {
  asset: ProjectAsset;
  packageId: string;
  defName: string;
}): ProjectAsset {
  const parsed = parseRaceTextureAssetRole(params.asset.role);
  if (!parsed) return params.asset;

  const paths = normalizeRaceTexturePaths({
    packageId: params.packageId,
    defName: params.defName,
    variant: parsed.variant
  });
  const selected = paths[parsed.group].directions[parsed.direction];

  return {
    ...params.asset,
    normalizedFileName: selected.normalizedFileName,
    exportPath: selected.exportPath,
    xmlTexturePath: selected.xmlTexturePath
  };
}


export const itemTextureDirections: ItemTextureDirection[] = ["single", "front", "side", "back"];

export const itemTextureDirectionLabels: Record<ItemTextureDirection, string> = {
  single: "单张图 Single",
  front: "正面 Front",
  side: "侧面 Side",
  back: "背面 Back"
};

export function makeItemTextureAssetRole(itemId: string, direction: ItemTextureDirection): ItemTextureAssetRole {
  return `item.${itemId}.${direction}`;
}

export function parseItemTextureAssetRole(role: AssetRole): { itemId: string; direction: ItemTextureDirection } | null {
  const parts = role.split(".");
  if (parts.length !== 3 || parts[0] !== "item") return null;
  const itemId = parts[1];
  const direction = parts[2] as ItemTextureDirection;
  if (!itemId || !itemTextureDirections.includes(direction)) return null;
  return { itemId, direction };
}

export function normalizeItemTexturePaths(params: {
  packageId: string;
  defName: string;
  itemKind: string;
}) {
  const packageId = sanitizePackageId(params.packageId);
  const defName = sanitizeThingDefName(params.defName);
  const kindFolder = itemKindToFolder(params.itemKind);
  const base = `${packageId}/Items/${kindFolder}/${defName}`;
  const directionalBase = `${base}/${defName}`;
  const singleBase = `${base}/${defName}`;

  return {
    single: {
      normalizedFileName: `${defName}.png`,
      exportPath: `Textures/${singleBase}.png`,
      xmlTexturePath: singleBase
    },
    front: makeItemDirectionalPath(directionalBase, defName, "front"),
    side: makeItemDirectionalPath(directionalBase, defName, "side"),
    back: makeItemDirectionalPath(directionalBase, defName, "back")
  };
}

function makeItemDirectionalPath(xmlTexturePath: string, defName: string, direction: RaceTextureDirection) {
  const suffix = directionToRimWorldSuffix[direction];
  return {
    normalizedFileName: `${defName}_${suffix}.png`,
    exportPath: `Textures/${xmlTexturePath}_${suffix}.png`,
    xmlTexturePath
  };
}

function itemKindToFolder(kind: string): string {
  if (kind === "hair") return "Hair";
  if (kind === "apparel") return "Apparel";
  if (kind === "food") return "Food";
  if (kind === "weapon") return "Weapons";
  return "Generic";
}

export function createItemAsset(params: {
  file: File;
  role: ItemTextureAssetRole;
  packageId: string;
  defName: string;
  itemKind: string;
}): ProjectAsset {
  const parsed = parseItemTextureAssetRole(params.role);
  if (!parsed) throw new Error(`Invalid item texture role: ${params.role}`);

  const paths = normalizeItemTexturePaths({ packageId: params.packageId, defName: params.defName, itemKind: params.itemKind });
  const selected = paths[parsed.direction];

  return {
    id: crypto.randomUUID(),
    role: params.role,
    originalName: params.file.name,
    mimeType: params.file.type || "image/png",
    sourceKind: "browser-file",
    file: params.file,
    normalizedFileName: selected.normalizedFileName,
    exportPath: selected.exportPath,
    xmlTexturePath: selected.xmlTexturePath,
    previewUrl: URL.createObjectURL(params.file)
  };
}

export function refreshItemAssetPath(params: {
  asset: ProjectAsset;
  packageId: string;
  defName: string;
  itemKind: string;
}): ProjectAsset {
  const parsed = parseItemTextureAssetRole(params.asset.role);
  if (!parsed) return params.asset;

  const paths = normalizeItemTexturePaths({ packageId: params.packageId, defName: params.defName, itemKind: params.itemKind });
  const selected = paths[parsed.direction];
  return {
    ...params.asset,
    normalizedFileName: selected.normalizedFileName,
    exportPath: selected.exportPath,
    xmlTexturePath: selected.xmlTexturePath
  };
}

export function getGeneratedWestItemTexturePath(asset: ProjectAsset): string | null {
  const parsed = parseItemTextureAssetRole(asset.role);
  if (!parsed || parsed.direction !== "side") return null;
  return `Textures/${asset.xmlTexturePath}_west.png`;
}


export function normalizeStorytellerPortraitPaths(params: { packageId: string; defName: string }) {
  const packageId = sanitizePackageId(params.packageId);
  const defName = sanitizeDefName(params.defName || "CustomStoryteller");
  const base = `${packageId}/Storytellers/${defName}`;
  return {
    large: {
      normalizedFileName: `${defName}.png`,
      exportPath: `Textures/${base}.png`,
      xmlTexturePath: base
    },
    tiny: {
      normalizedFileName: `${defName}_Tiny.png`,
      exportPath: `Textures/${base}_Tiny.png`,
      xmlTexturePath: `${base}_Tiny`
    }
  };
}

export function parseStorytellerPortraitRole(role: AssetRole): "large" | "tiny" | null {
  if (role === "storyteller.large") return "large";
  if (role === "storyteller.tiny") return "tiny";
  return null;
}

export function createStorytellerAsset(params: {
  file: File;
  role: StorytellerPortraitRole;
  packageId: string;
  defName: string;
}): ProjectAsset {
  const kind = parseStorytellerPortraitRole(params.role);
  if (!kind) throw new Error(`Invalid storyteller portrait role: ${params.role}`);
  const paths = normalizeStorytellerPortraitPaths({ packageId: params.packageId, defName: params.defName });
  const selected = paths[kind];

  return {
    id: crypto.randomUUID(),
    role: params.role,
    originalName: params.file.name,
    mimeType: params.file.type || "image/png",
    sourceKind: "browser-file",
    file: params.file,
    normalizedFileName: selected.normalizedFileName,
    exportPath: selected.exportPath,
    xmlTexturePath: selected.xmlTexturePath,
    previewUrl: URL.createObjectURL(params.file)
  };
}

export function refreshStorytellerAssetPath(params: {
  asset: ProjectAsset;
  packageId: string;
  defName: string;
}): ProjectAsset {
  const kind = parseStorytellerPortraitRole(params.asset.role);
  if (!kind) return params.asset;
  const paths = normalizeStorytellerPortraitPaths({ packageId: params.packageId, defName: params.defName });
  const selected = paths[kind];
  return {
    ...params.asset,
    normalizedFileName: selected.normalizedFileName,
    exportPath: selected.exportPath,
    xmlTexturePath: selected.xmlTexturePath
  };
}
